version: "3"

services:
    app:
        image: lpcuong2106/laravel_ban_chuoi
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - mynet
    #nginx service
    webserver:
        image: nginx:1.17-alpine
        restart: unless-stopped
        ports:
            - "9000:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - mynet
     # DB UI management service
    phpmyadmin:
        depends_on:
          - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - 8088:80
        env_file:
          - .env
        environment:
          PMA_HOST: db
          PMA_PORTS: 3306
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_ROOT_PASSWORD: rootpass
        networks:
          - mynet
    #mysql
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: rootpass
        expose:
            - 3306
        volumes:
            - .docker/data/db:/var/lib/mysql/
        networks:
            - mynet
networks:
    mynet:
        driver: bridge
